services:
  web:
    build: .
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build:
      context: .
      dockerfile: VagtPlan.ApiService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JWT__AUDIENCE=${JWT_AUDIENCE}
      - JWT__ISSUER=${JWT_ISSUER}
      - JWT__SECRET=${JWT_SECRET}
      - JWT__EXPIRE__MINUTES=${JWT_EXPIRE_MINUTES}
      - ADMIN__AUTH__USERNAME=${ADMIN_AUTH_USERNAME}
      - ADMIN__AUTH__PASSWORD=${ADMIN_AUTH_PASSWORD}
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge

volumes:
  db-data: