services:
  postgres:
    image: postgres:16-alpine
    container_name: vagtplanDB
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build:
      context: .
      dockerfile: VagtPlan.ApiService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JWT__AUDIENCE=${JWT_AUDIENCE}
      - JWT__ISSUER=${JWT_ISSUER}
      - JWT__SECRET=${JWT_SECRET}
      - JWT__EXPIRE__MINUTES=${JWT_EXPIRE_MINUTES}
      - ADMIN__AUTH__USERNAME=${ADMIN_AUTH_USERNAME}
      - ADMIN__AUTH__PASSWORD=${ADMIN_AUTH_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge

volumes:
  db-data: