using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApiService.Migrations
{
    /// <inheritdoc />
    public partial class FixNamesAndSpecialWish : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $EF$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Statuses' AND column_name = 'Color'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Statuses' AND column_name = 'Colour'
                    ) THEN
                        ALTER TABLE "Statuses" RENAME COLUMN "Color" TO "Colour";
                    END IF;
                END
                $EF$;

                CREATE TABLE IF NOT EXISTS "SpecialWishes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "StartDate" timestamp with time zone NOT NULL,
                    "EndDate" timestamp with time zone NOT NULL,
                    "DayOfWeek" text NOT NULL,
                    "StatusId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_SpecialWishes" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_SpecialWishes_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_SpecialWishes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_SpecialWishes_StatusId" ON "SpecialWishes" ("StatusId");
                CREATE INDEX IF NOT EXISTS "IX_SpecialWishes_UserId" ON "SpecialWishes" ("UserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $EF$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'SpecialWishes')
                       AND NOT EXISTS (SELECT 1 FROM "SpecialWishes" LIMIT 1) THEN
                        DROP TABLE "SpecialWishes";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Statuses' AND column_name = 'Colour'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Statuses' AND column_name = 'Color'
                    ) THEN
                        ALTER TABLE "Statuses" RENAME COLUMN "Colour" TO "Color";
                    END IF;
                END
                $EF$;
                """);
        }
    }
}
