using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApiService.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Departments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Statuses" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "Color" text NOT NULL,
                    "IsAvailable" boolean NOT NULL,
                    "Default" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "UserRole" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_UserRole" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "WorkTimes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DepartmentId" integer NOT NULL,
                    "StartTime" time without time zone NOT NULL,
                    "EndTime" time without time zone NOT NULL,
                    "DayOfWeek" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_WorkTimes" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_WorkTimes_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "Users" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "Password" text,
                    "VactionDays" integer NOT NULL,
                    "DepartmentId" integer NOT NULL,
                    "UserRoleId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Users_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_Users_UserRole_UserRoleId" FOREIGN KEY ("UserRoleId") REFERENCES "UserRole" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "Substitutes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Date" timestamp with time zone NOT NULL,
                    "StartTime" time without time zone NOT NULL,
                    "EndTime" time without time zone NOT NULL,
                    "SubstitutedName" text,
                    "SubstituteId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Substitutes" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Substitutes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "Wishes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DayOfWeek" text NOT NULL,
                    "StatusId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Wishes" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Wishes_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_Wishes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "Workdays" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Date" timestamp with time zone NOT NULL,
                    "StartTime" time without time zone NOT NULL,
                    "EndTime" time without time zone NOT NULL,
                    "StatusId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Workdays" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Workdays_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_Workdays_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_Substitutes_UserId" ON "Substitutes" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_Users_DepartmentId" ON "Users" ("DepartmentId");
                CREATE INDEX IF NOT EXISTS "IX_Users_UserRoleId" ON "Users" ("UserRoleId");
                CREATE INDEX IF NOT EXISTS "IX_Wishes_StatusId" ON "Wishes" ("StatusId");
                CREATE INDEX IF NOT EXISTS "IX_Wishes_UserId" ON "Wishes" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_Workdays_StatusId" ON "Workdays" ("StatusId");
                CREATE INDEX IF NOT EXISTS "IX_Workdays_UserId" ON "Workdays" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_WorkTimes_DepartmentId" ON "WorkTimes" ("DepartmentId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $EF$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Substitutes')
                       AND NOT EXISTS (SELECT 1 FROM "Substitutes" LIMIT 1) THEN
                        DROP TABLE "Substitutes";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Wishes')
                       AND NOT EXISTS (SELECT 1 FROM "Wishes" LIMIT 1) THEN
                        DROP TABLE "Wishes";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Workdays')
                       AND NOT EXISTS (SELECT 1 FROM "Workdays" LIMIT 1) THEN
                        DROP TABLE "Workdays";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'WorkTimes')
                       AND NOT EXISTS (SELECT 1 FROM "WorkTimes" LIMIT 1) THEN
                        DROP TABLE "WorkTimes";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Users')
                       AND NOT EXISTS (SELECT 1 FROM "Users" LIMIT 1) THEN
                        DROP TABLE "Users";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Statuses')
                       AND NOT EXISTS (SELECT 1 FROM "Statuses" LIMIT 1) THEN
                        DROP TABLE "Statuses";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Departments')
                       AND NOT EXISTS (SELECT 1 FROM "Departments" LIMIT 1) THEN
                        DROP TABLE "Departments";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'UserRole')
                       AND NOT EXISTS (SELECT 1 FROM "UserRole" LIMIT 1) THEN
                        DROP TABLE "UserRole";
                    END IF;
                END
                $EF$;
                """);
        }
    }
}
